spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
      retry:
        enable: true
        max-attempts: 5
        initial-interval: 1000
        max-interval: 5000
        multiplier: 1.5