server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_batis_example?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
